spring.application.name=klikkas
server.port=5001

spring.datasource.url=jdbc:postgresql://localhost:5432/klikkas
spring.datasource.username=jonsnow
spring.datasource.password=jonsnow

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=false

logging.level.org.flywaydb=DEBUG
