spring.application.name=klikkas
server.port=${SERVER_PORT:5001}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=false

logging.level.org.flywaydb=${FLYWAY_LOG_LEVEL:INFO}
